### ISSUE TITLE
Xeric's Talisman is reporting as uncharged on the new map

### ISSUE THREAD

**Issue by Norkotah** [MJHylkema/spirit-tree-map#22]
I use this in conjunction with the Easy Teleports plugin that lets you rename teleports. Xeric's Talisman is reporting as uncharged and unusable when accessed from the new map. I can use the teleport options from the equipped context menus and the talisman is fully charged.

If I disable the Xeric's Talisman renames it works, but then I lose the renames on the worn items right click menu. I usually use it equipped, so that map might be a dealbreaker for me. I'd rather have the right-click renames than the map if I have to only pick one. 

Since the names you use in your map are the same renames I chose for Easy Teleports, could you just change the right-click teleport menu options to the names you use in this map so I can just disable the renames in East Teleports? I''ve gotten used to teleporting to Hosidius rather than Xeric's Glade.

![image](https://github.com/MJHylkema/spirit-tree-map/assets/8877555/f2a9062f-a0c8-47ed-a321-44a85290ab88)

Also I want to clarify I am not pointing fingers at all. If the problem lies with the Easy Teleports plugin rather than yours, I'll raise the issue over there instead. Also, all the other teleport maps work fine for me. The Xeric's Talisman is the only map on an item without unlimited charges though. Does that have something to do with it?

**Comment by Norkotah** [comment]
![image](https://github.com/MJHylkema/spirit-tree-map/assets/8877555/0b8bd544-6052-49fb-9612-5751eb378b0d)

This is what happens when I click on a location.

**Comment by MJHylkema** [comment]
Hi @Norkotah, thanks for raising this. It has already been brought to my attention and I plan to fix this promptly.

The issue has arisen because I match with the existing teleport buttons based of their default names, e.g. "Xeric's Glade". Because the teleport buttons have been renamed via Easy Teleports, Teleport Maps doesn't think the teleport is available and therefore shows the unavailable icon and my inserted examine option. I will need to add an alias list for each location so that it still matches even if the teleport button has been renamed to "Hosidius" for example. 

In the meantime, I suggest you just turn off the Xerics Map for the Teleport Maps plugin until I patch this. 

![image](https://github.com/MJHylkema/spirit-tree-map/assets/20365453/22855c03-97e7-42c5-aa40-3e9869179be3)

**Comment by MJHylkema** [comment]
Reopening issue until plugin-hub PR is merged.

**Comment by MJHylkema** [comment]
Fix should now be live 👍
